CATEGORY_OTHER = 0
CATEGORY_TREASURY = 1
CATEGORY_REGISTRATION = 2
CATEGORY_EVENTS = 3
CATEGORY_FACILITIES = 4
CATEGORY_UNITY = 5
CATEGORY_HOSPITALITY = 6
CATEGORY_GRAPHICS = 7
CATEGORY_TRANSPORTATION = 8
CATEGORY_LITERATURE = 9
CATEGORY_MERCHANDISE = 10
CATEGORY_PROGRAMS = 11
CATEGORY_MISC = 12
CATEGORY_OUTREACH = 13
CATEGORY_ACCESSIBILITY = 14
CATEGORY_ENTERTAINMENT = 15

CATEGORY_TO_INT = dict(
    other=CATEGORY_OTHER,
    treasury=CATEGORY_TREASURY,
    registration=CATEGORY_REGISTRATION,
    events=CATEGORY_EVENTS,
    facilities=CATEGORY_FACILITIES,
    unity=CATEGORY_UNITY,
    hospitality=CATEGORY_HOSPITALITY,
    graphics=CATEGORY_GRAPHICS,
    transportation=CATEGORY_TRANSPORTATION,
    literature=CATEGORY_LITERATURE,
    merch=CATEGORY_MERCHANDISE,
    programs=CATEGORY_PROGRAMS,
    misc=CATEGORY_MISC,
    outreach=CATEGORY_OUTREACH,
    accessibility=CATEGORY_ACCESSIBILITY,
    entertainment=CATEGORY_ENTERTAINMENT,
)

CATEGORY_TO_NAME = dict([
    (CATEGORY_OTHER, 'other',),
    (CATEGORY_TREASURY, 'treasury',),
    (CATEGORY_REGISTRATION, 'registration',),
    (CATEGORY_EVENTS, 'events',),
    (CATEGORY_FACILITIES, 'facilities',),
    (CATEGORY_UNITY, 'unity',),
    (CATEGORY_HOSPITALITY, 'hospitality',),
    (CATEGORY_GRAPHICS, 'graphics',),
    (CATEGORY_TRANSPORTATION, 'transportation',),
    (CATEGORY_LITERATURE, 'literature',),
    (CATEGORY_MERCHANDISE, 'mercahndise',),
    (CATEGORY_PROGRAMS, 'programs',),
    (CATEGORY_MISC, 'misc',),
    (CATEGORY_OUTREACH, 'outreach',),
    (CATEGORY_ACCESSIBILITY, 'accessibility',),
    (CATEGORY_ENTERTAINMENT, 'entertainment',),
])

ACTUAL_GOOGLE_ID='1OuWH4SfwBCiimlmAaCj5mezWWr2V8mMr5-z5n9SGv-s'
PROJECTED_GOOGLE_ID='1ubIVAL7zjEyk7ZU-KAz1hshfFp7f4k9b7A1MCgUC6FY'